export const PROVINCIAS_POR_COMUNIDAD: Record<string, string[]> = {
  Andalucía: ['Almería', 'Cádiz', 'Córdoba', 'Granada', 'Huelva', 'Jaén', 'Málaga', 'Sevilla'],
  Aragón: ['Huesca', 'Teruel', 'Zaragoza'],
  Asturias: ['Asturias', 'Asturies'],
  Baleares: ['Baleares', 'Balears', 'Illes Balears'],
  Canarias: ['Las Palmas', 'Santa Cruz de Tenerife'],
  Cantabria: ['Cantabria'],
  'Castilla-La Mancha': ['Albacete', 'Ciudad Real', 'Cuenca', 'Guadalajara', 'Toledo'],
  'Castilla y León': ['Ávila', 'Burgos', 'León', 'Palencia', 'Salamanca', 'Segovia', 'Soria', 'Valladolid', 'Zamora'],
  Cataluña: ['Barcelona', 'Girona', 'Lleida', 'Tarragona'],
  'Comunidad Valenciana': ['Alicante', 'Castellón', 'Valencia', 'Alacant', 'Castelló', 'València'],
  Extremadura: ['Badajoz', 'Cáceres'],
  Galicia: ['A Coruña', 'Lugo', 'Ourense', 'Pontevedra'],
  Madrid: ['Madrid'],
  Murcia: ['Murcia'],
  Navarra: ['Navarra', 'Nafarroa'],
  'País Vasco': ['Álava', 'Guipúzcoa', 'Vizcaya', 'Araba', 'Gipuzkoa', 'Bizkaia'],
  'La Rioja': ['La Rioja'],
  Ceuta: ['Ceuta'],
  Melilla: ['Melilla'],
};

export const PROVINCIA_NORMALIZACION: Record<string, string> = {
  'Almería': 'Almería',
  'Cádiz': 'Cádiz',
  'Córdoba': 'Córdoba',
  'Granada': 'Granada',
  'Huelva': 'Huelva',
  'Jaén': 'Jaén',
  'Málaga': 'Málaga',
  'Sevilla': 'Sevilla',
  'Huesca': 'Huesca',
  'Teruel': 'Teruel',
  'Zaragoza': 'Zaragoza',
  'Asturias': 'Asturias',
  'Asturies': 'Asturias',
  'Baleares': 'Baleares',
  'Balears': 'Baleares',
  'Illes Balears': 'Baleares',
  'Las Palmas': 'Las Palmas',
  'Santa Cruz de Tenerife': 'Santa Cruz de Tenerife',
  'Cantabria': 'Cantabria',
  'Albacete': 'Albacete',
  'Ciudad Real': 'Ciudad Real',
  'Cuenca': 'Cuenca',
  'Guadalajara': 'Guadalajara',
  'Toledo': 'Toledo',
  'Ávila': 'Ávila',
  'Burgos': 'Burgos',
  'León': 'León',
  'Palencia': 'Palencia',
  'Salamanca': 'Salamanca',
  'Segovia': 'Segovia',
  'Soria': 'Soria',
  'Valladolid': 'Valladolid',
  'Zamora': 'Zamora',
  'Barcelona': 'Barcelona',
  'Girona': 'Girona',
  'Lleida': 'Lleida',
  'Tarragona': 'Tarragona',
  'Alicante': 'Alicante',
  'Alacant': 'Alicante',
  'Castellón': 'Castellón',
  'Castelló': 'Castellón',
  'Valencia': 'Valencia',
  'València': 'Valencia',
  'Badajoz': 'Badajoz',
  'Cáceres': 'Cáceres',
  'A Coruña': 'A Coruña',
  'Lugo': 'Lugo',
  'Ourense': 'Ourense',
  'Pontevedra': 'Pontevedra',
  'Madrid': 'Madrid',
  'Murcia': 'Murcia',
  'Navarra': 'Navarra',
  'Nafarroa': 'Navarra',
  'Álava': 'Álava',
  'Araba': 'Álava',
  'Guipúzcoa': 'Guipúzcoa',
  'Gipuzkoa': 'Guipúzcoa',
  'Vizcaya': 'Vizcaya',
  'Bizkaia': 'Vizcaya',
  'La Rioja': 'La Rioja',
  'Ceuta': 'Ceuta',
  'Melilla': 'Melilla',
};

export const COMUNIDADES = Object.keys(PROVINCIAS_POR_COMUNIDAD);
