import { TERRITORIOS_ESPANA } from '../data/territorios';

export const PROVINCIAS_POR_COMUNIDAD: Record<string, string[]> = TERRITORIOS_ESPANA.reduce((acc, comunidad) => {
  acc[comunidad.nombre] = comunidad.provincias.flatMap(p => [p.nombre, ...(p.islas || [])]);
  return acc;
}, {} as Record<string, string[]>);

export const COMUNIDADES = TERRITORIOS_ESPANA.map(c => c.nombre);

export const PROVINCIA_NORMALIZACION: Record<string, string> = {
  'Almería': 'Almería',
  'Cádiz': 'Cádiz',
  'Córdoba': 'Córdoba',
  'Granada': 'Granada',
  'Huelva': 'Huelva',
  'Jaén': 'Jaén',
  'Málaga': 'Málaga',
  'Sevilla': 'Sevilla',
  'Huesca': 'Huesca',
  'Teruel': 'Teruel',
  'Zaragoza': 'Zaragoza',
  'Asturias': 'Asturias',
  'Asturies': 'Asturias',
  'Baleares': 'Illes Balears',
  'Balears': 'Illes Balears',
  'Illes Balears': 'Illes Balears',
  'Las Palmas': 'Las Palmas',
  'Santa Cruz de Tenerife': 'Santa Cruz de Tenerife',
  'Cantabria': 'Cantabria',
  'Albacete': 'Albacete',
  'Ciudad Real': 'Ciudad Real',
  'Cuenca': 'Cuenca',
  'Guadalajara': 'Guadalajara',
  'Toledo': 'Toledo',
  'Ávila': 'Ávila',
  'Burgos': 'Burgos',
  'León': 'León',
  'Palencia': 'Palencia',
  'Salamanca': 'Salamanca',
  'Segovia': 'Segovia',
  'Soria': 'Soria',
  'Valladolid': 'Valladolid',
  'Zamora': 'Zamora',
  'Barcelona': 'Barcelona',
  'Girona': 'Girona',
  'Lleida': 'Lleida',
  'Lérida': 'Lleida',
  'Tarragona': 'Tarragona',
  'Alicante': 'Alicante/Alacant',
  'Alacant': 'Alicante/Alacant',
  'Alicante/Alacant': 'Alicante/Alacant',
  'Castellón': 'Castellón/Castelló',
  'Castelló': 'Castellón/Castelló',
  'Castellón/Castelló': 'Castellón/Castelló',
  'Valencia': 'Valencia/València',
  'València': 'Valencia/València',
  'Valencia/València': 'Valencia/València',
  'Badajoz': 'Badajoz',
  'Cáceres': 'Cáceres',
  'A Coruña': 'A Coruña',
  'La Coruña': 'A Coruña',
  'Coruña': 'A Coruña',
  'Lugo': 'Lugo',
  'Ourense': 'Ourense',
  'Orense': 'Ourense',
  'Pontevedra': 'Pontevedra',
  'Madrid': 'Madrid',
  'Murcia': 'Murcia',
  'Navarra': 'Navarra',
  'Nafarroa': 'Navarra',
  'Álava': 'Álava/Araba',
  'Araba': 'Álava/Araba',
  'Álava/Araba': 'Álava/Araba',
  'Vizcaya': 'Bizkaia',
  'Bizkaia': 'Bizkaia',
  'Guipúzcoa': 'Gipuzkoa',
  'Gipuzkoa': 'Gipuzkoa',
  'La Rioja': 'La Rioja',
  'Ceuta': 'Ceuta',
  'Melilla': 'Melilla'
};
